### ISSUE TITLE
Input Group

### ISSUE THREAD

**Issue by Momjo** [Momjo/TODO-List#5]
why alerts the input if i use input groups in the form ?

![screen shot 2018-05-30 at 16 24 15](https://user-images.githubusercontent.com/19407713/40726401-f0721212-6425-11e8-91c0-e30c5c31cf06.png)

**Comment by AmirSavand** [comment]
That's standard of way of bootstrap.

**Comment by Momjo** [comment]
then if I want to have the button and input field next to each other like input-group then I have to do it with CSS, or ??

**Comment by AmirSavand** [comment]
Here you go: https://getbootstrap.com/docs/4.1/components/input-group/#button-addons

If you want to use different size or septate them, use `.row` and `.col` (grid system) inside `.from-group`.
